# Generated by Django 5.0.4 on 2024-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_executor_alter_task_owner'),
        ('users', '0007_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.task', verbose_name='tasks'),
        ),
    ]
