# Generated by Django 5.0.4 on 2024-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_executor'),
        ('users', '0008_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task', verbose_name='tasks'),
        ),
    ]
