# Generated by Django 5.0.4 on 2024-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('assigned', 'assigned'), ('completed', 'completed')], default='created', verbose_name='status'),
        ),
    ]
