# Generated by Django 5.0.4 on 2024-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_executor_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='owner'),
        ),
    ]
