# Generated by Django 5.0.4 on 2024-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_executor_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('worked', 'worked'), ('completed', 'completed')], default='created', verbose_name='status'),
        ),
    ]
