# Generated by Django 5.0.4 on 2024-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(default='not_yet_appointed', max_length=40, verbose_name='executor'),
        ),
    ]
