# Generated by Django 4.2.7 on 2024-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_executor_remove_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.CharField(default='not_yet_appointed', max_length=40, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='owner'),
        ),
    ]
